name: Deploy

on:
  push: {branches: [main]}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
      - run: npm ci
      # Set up caching to automatically re-use existing data from previous builds
      # - id: date
      #   run: echo "date=$(TZ=America/Los_Angeles date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
      # - id: cache-data
      #   uses: actions/cache@v4
      #   with:
      #     path: src/.observablehq/cache
      #     key: data-${{ hashFiles('src/data/*') }}-${{ steps.date.outputs.date }}
      - run: npm run build
      - name: Deploy to Observable Cloud
        # This parameter to `--message` will use the latest commit message
        run: npm run deploy -- --message "$(git log -1 --pretty=%s)"
        env:
          OBSERVABLE_TOKEN: ${{ secrets.OBSERVABLE_TOKEN }}